chore: Typescript Cleanup Part 3 of 3 for Visualization Type error Part 2
v-prachin/accessibility-insights-web pull request #1
Opened 2024-04-04 07:04 UTC by v-prachin

#### Details

Typescript Cleanup Part 3 of 3 
We have total 90 errors remaining in 53 files.

##### Motivation
Visualization type was having error when negative value is assigned to it, so changed the datatype to number along with visualization type to overcome the errors. The test cases are passing successfully and able to observe in console log that the value of e.g test = -1 is coming -1 only even after changing the datatype for visualizationType.

1. src/tests/unit/tests/injected/analyzer-state-update-handler.test.ts (5)
2. src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts (1)
3. src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts (1)
4. src/tests/unit/tests/injected/selector-map-helper.test.ts (4)
5. src/tests/unit/tests/injected/target-page-visualization-updater.test.ts	(1)
6. src/tests/unit/tests/injected/visualization-state-change-handler.test.ts (2)
7. src/tests/unit/tests/injected/visualization-type-drawer-registrar.test.ts (1)
8. src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx (8)
9. src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts (2)

Thus, total number of errors covered as part of this user story: **25**

##### Context

#### Pull request checklist

- [x] Addresses an existing issue: #(https://github.com/microsoft/accessibility-insights-web/pull/6611)
- [x] Ran `yarn fastpass`
- [x] Added/updated relevant unit test(s) (and ran `yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] PR title *AND* final merge commit title both start with a semantic tag (`fix:`, `chore:`, `feat(feature-name):`, `refactor:`). See `CONTRIBUTING.md`.
- [n/a] (UI changes only) Added screenshots/GIFs to description above
- [n/a] (UI changes only) Verified usability with NVDA/JAWS

2024-04-10 23:16 UTC, v-viyada requested changes

2024-04-10 23:16 UTC, v-viyada commented on src/injected/analyzers/analyzer.ts
> +    testType: VisualizationType | number;
```suggestion
    testType: VisualizationType;
```

2024-04-10 23:16 UTC, v-viyada commented on src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
> +        const visualizationTypeStub: number = -2;
```suggestion
        const visualizationTypeStub= 0;
```

2024-04-10 23:16 UTC, v-viyada commented on src/tests/unit/tests/injected/analyzer-state-update-handler.test.ts
> +        tearDownCallback(configMock.object, type1, requirementConfig);
```suggestion
        tearDownCallback(configMock.object, 0, requirementConfig);
```

2024-04-10 23:16 UTC, v-viyada commented on src/tests/unit/tests/injected/analyzer-state-update-handler.test.ts
> +        const type1: number = -1;
```suggestion
```

2024-04-10 23:16 UTC, v-viyada commented on src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx
> +    const firstVisualizationTypeStub: number = -1;
```suggestion
    const firstVisualizationTypeStub: number = 0;
```

2024-04-10 23:16 UTC, v-viyada commented on src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx
> +    const secondVisualizationTypeStub: number = -2;
```suggestion
    const secondVisualizationTypeStub: number = 1;
```

2024-04-10 23:16 UTC, v-viyada commented on src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx
> +    const thirdAlwaysDisabledVisualizationTypeStub: number = -3;
```suggestion
    const thirdAlwaysDisabledVisualizationTypeStub: number = 2;
```

2024-04-12 09:43 UTC, v-prachin commented on src/injected/analyzers/analyzer.ts
> +    testType: VisualizationType | number;
Made the suggested change

2024-04-12 09:44 UTC, v-prachin commented on src/tests/unit/tests/injected/analyzer-state-update-handler.test.ts
> +        tearDownCallback(configMock.object, type1, requirementConfig);
Made the suggested change

2024-04-12 09:44 UTC, v-prachin commented on src/tests/unit/tests/injected/analyzer-state-update-handler.test.ts
> +        const type1: number = -1;
Made the suggested change

2024-04-12 09:44 UTC, v-prachin commented on src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx
> +    const firstVisualizationTypeStub: number = -1;
Made the suggested change

2024-04-12 09:44 UTC, v-prachin commented on src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx
> +    const secondVisualizationTypeStub: number = -2;
Made the suggested change

2024-04-12 09:44 UTC, v-prachin commented on src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx
> +    const thirdAlwaysDisabledVisualizationTypeStub: number = -3;
Made the suggested change

2024-04-15 06:05 UTC, merged